library(wordcloud)
data <- read.table(file="CPPFlags.data",col.names=c("word","frequency"))
svg(filename="CPPFlags.svg")
pal <- brewer.pal(4,"Set1")
wordcloud(data$word,data$frequency,min.freq=30,random.order=FALSE,colors=c("black","red","darkgreen","blue"),random.color=TRUE)
